# Generated by Django 4.0 on 2022-02-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('state', models.CharField(choices=[('A', 'Todo'), ('B', 'In Progress'), ('C', 'Done'), ('D', 'Close')], default='A', max_length=4, verbose_name='Estado')),
                ('coment', models.CharField(max_length=200, verbose_name='Comentario')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
