# Generated by Django 4.0 on 2022-02-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='date_expire',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
    ]
