# Generated by Django 4.0 on 2022-02-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaToDo', '0002_lista_date_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='coment',
            field=models.TextField(),
        ),
    ]
